<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:msxsl="urn:schemas-microsoft-com:xslt" exclude-result-prefixes="msxsl"
>

	<xsl:include href="../layout.xslt"/>

	<xsl:variable name="topic" select="/records/item[@name='topic']/topic" />
	<xsl:variable name="assoc" select="/records/item[@name='assoc']/association" />
	<xsl:variable name="meta" select="$topic/metadata/metadata" />

	<xsl:variable name="new-assoc-id" select="/records/item[@name='new-assoc-id']/text-data" />

	<xsl:template  match="@* | node()" mode="view"></xsl:template>
	<xsl:template  match="@* | node()" mode="view-head"></xsl:template>
	<xsl:template  match="@* | node()" mode="view-navigation"></xsl:template>


	<xsl:template match="records" mode="view-head">
		<link rel="stylesheet" href="{$app-path}/resources/css/public/topic/edit.css" />
		<title>Some Title</title>
	</xsl:template>

	<xsl:template match="item[@name='navigation-view']" mode="view-navigation">
		<h4>Relations</h4>
		<ul>
			<xsl:apply-templates select="records/item" mode="view-navigation" />
		</ul>
	</xsl:template>

	<xsl:template match="item[@name='navigation-view']/records/item" mode="view-navigation">
		<li>
			<xsl:value-of select="@name"/>
			<ul>
				<xsl:apply-templates select="records/item" mode="view-navigation" />
			</ul>
		</li>
	</xsl:template>

	<xsl:template match="item[@name='navigation-view']/records/item/records/item" mode="view-navigation">
		<li>
			<xsl:value-of select="@name"/>
			<ul>
				<xsl:apply-templates select="list/association" mode="view-navigation" />
			</ul>
		</li>
	</xsl:template>

	<xsl:template match="item[@name='navigation-view']/records/item/records/item/list/association" mode="view-navigation">
		<li>
			<a href="?id={@reference}">
				<xsl:value-of select="metadata/metadata[@name='label']/@value"/>
			</a>
		</li>
	</xsl:template>

	<!-- ENTRY POINT FROM LAYOUT -->
	<xsl:template match="records" mode="view">
		<xsl:apply-templates select="item[@name='topic']/topic" mode="view" />
	</xsl:template>

	<xsl:template match="records" mode="view">
		<div class="hero-unit">
			<h1>
				Create Association
			</h1>
		</div>

		<div class="container">
			<ul class="nav nav-tabs">
				<li>
					<a href="{$app-path}/public/topic/view.aspx?id=home">Home</a>
				</li>
				<li class="dropdown active">
					<a
						href="#"
						class="dropdown-toggle"
						data-toggle="dropdown"
					>
						Create <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li>
							<a href="{$app-path}/public/topic/create.aspx?id={$topic/@id}">Topic</a>
						</li>
						<li class="active">
							<a href="#">Association</a>
						</li>
					</ul>
				</li>
			</ul>
		</div>

		<div class="container">
			<div class="row">
				<div class="span6 col left-col">
					<xsl:apply-templates select="/records/item[@name='errors']/list" />
					<xsl:apply-templates select="/records/item[@name='messages']/list" />
					<h4>Association Identity</h4>
					<p>
						Each association has a unique identity (ID) which is can be refered by.
						The system will generate a long random identity for you, and it is
						not normal to use an identity for associations other than that
						generated by the system.
					</p>
					<h4>Association Label</h4>
					<p>
						You should enter a label of your own choosing which will be used for the current language and scope of the topic.
						More details control of labels can be achieved by editing the <a href="{$app-path}/association/edit.aspx?id={$topic/@id}">association metadata</a>.
					</p>
				</div>
				<div class="span6 col center-col">
					<form method="post" action="{$app-path}/public/association/create.aspx" class="form-horizontal">
						<input type="hidden" name="id" value="{$topic/@id}" />
						<input type="hidden" name="scope" value="default" />
						<fieldset>
							<legend>Association details.</legend>
							<div class="control-group">
								<label for="assoc" class="control-label">ID</label>
								<div class="controls">
									<input type="text" class="span4"  name="assoc" value="{/records/item[@name='new-assoc-id']/text-data}" />
								</div>
							</div>
							<div class="control-group">
								<label for="parent" class="control-label">Parent</label>
								<div class="controls">
									<input type="text" name="parent" class="span4" value="{$topic/@id}"  />
								</div>
							</div>
							<!--<div class="control-group">
								<label for="parent" class="control-label">Scope</label>
								<div class="controls">
									<input type="text" name="scope" class="span4" value="{$assoc/@scope}"  />
								</div>
							</div>-->
							<div class="control-group">
								<label for="parent" class="control-label">Type</label>
								<div class="controls">
									<input type="text" name="type" class="span4" value="{$assoc/@type}"  />
								</div>
							</div>
							<div class="control-group">
								<label for="parent" class="control-label">Role</label>
								<div class="controls">
									<input type="text" name="role" class="span4" value="{$assoc/@role}"  />
								</div>
							</div>
							<div class="control-group">
								<label for="reference" class="control-label">Reference</label>
								<div class="controls">
									<input type="text" name="reference" class="span4" value="{$assoc/@reference}"  />
								</div>
							</div>
							<div class="control-group">
								<div class="controls">
									<input type="submit" class="span4 btn-large btn-primary" value="create" />
								</div>
							</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</xsl:template>

</xsl:stylesheet>
